TITLE 'JUDGES SCORES ON FISH PREPARED BY THREE METHODS';
DATA FISH;
  FISH +1;
  INFILE '/folders/myfolders/Multivariate/FISH.DAT';
  INPUT METHOD AROMA FLAVOR TEXTURE MOISTURE;
PROC GLM;
  CLASS METHOD;
  MODEL AROMA FLAVOR TEXTURE MOISTURE = METHOD;
  MANOVA H=METHOD/PRINTE PRINTH;
PROC FREQ DATA = FISH;
  TABLES METHOD;

Proc Print DATA=FISH; Id FISH; run;    
PROC GLM;
  CLASS METHOD;
  MODEL AROMA FLAVOR TEXTURE MOISTURE = METHOD;
  CONTRAST '1&2 VS 3' METHOD .5 .5 -1;
  CONTRAST '1 VS. 2' METHOD 1 -1 0;
  MANOVA H=_all_;  

RUN;
